name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # Change to "master" if your default branch is master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        # Forces static generation for GitHub Pages output
        run: |
          NITRO_PRESET=static npm run build
          cp .output/public/index.html .output/public/404.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './.output/public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
